[project]
name = "rtxi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "h5py>=3.13.0",
    "myplotlib>=1.5.0",
    "pandas>=2.2.3",
]
